stages:
  - install
  - build
  - test

install:
  stage: install
  image: node:25
  script:
    - npm ci

build:
  stage: build
  image: node:25
  script:
    - npm ci
    - npm run build

test:
  stage: test
  image: node:25
  script:
    - echo "Testing stage"
